fix: exit immediately instead of trying to cancel

diff --git a/.github/workflows/build-sysdots.yml b/.github/workflows/build-sysdots.yml
--- a/.github/workflows/build-sysdots.yml
+++ b/.github/workflows/build-sysdots.yml
@@ -39,17 +39,13 @@ jobs:
       - name: Checkout
         uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
 
-      - name: Check for priority
+      - name: Check for job overlap
         env:
             GH_TOKEN: ${{ github.token }}
         run: |
-          # look for any running AUR package builds for this repository
-          RUNNING_BAR=$(gh run list --workflow build-aurpkgs.yml --status in_progress --limit 1 --json databaseId -q '.[0].databaseId')
-          
-          if [ ! -z "$RUNNING_BAR" ]; then
-            echo "AUR package build is running!!! Cancelling to prevent job overlap."
-            gh run cancel ${{ github.run_id }}
-            sleep 10
+          if [ ! -z "$(gh run list --workflow build-aurpkgs.yml --status in_progress --limit 1 --json databaseId -q '.[0].databaseId')" ]; then
+            echo "AUR package build is running!!! Failing to prevent job overlap."
+            exit 1
           else
             echo "No AUR package builds detected."
           fi
